### PR TITLE
Upgrade to Java 17

### PR DESCRIPTION
**Pull request by kozmic**
Upgrade to Java 16 from Java 15
Upgrade Gradle and wrapper from to 6.8.3 to 7.5.1 (6.8.3 does not support Java 16)

Upgrade log4j-core from 2.17.1 to 2.19.0.
Upgrade org.beryx.runtime from 1.12.1 to 1.12.7

Remove module code in ArtishockCli as it's not compatible with Java 16.

### CODE REVIEW

**Review by alexanderkjall — COMMENTED** [review]
Shouldn't we upgrade to java 17 while we are at it, it's 17 that is the LTS release after all

**Comment by kozmic** [comment]
@alexanderkjall Good point! I've now updated the PR to Java 17.

**Review by alexanderkjall — APPROVED** [review]
LGTM

**Review by stiankri — APPROVED** [review]
LGTM

**Pull request merged**
